backup/igreja_dll/Site/Controllers/CelulaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RepositorioEF;
using business.classes.Abstrato;
using business.classes.Celulas;
using business.classes.Ministerio;
using business.classes.Celula;

namespace Site.Controllers
{
    [Authorize(Roles ="Admin")]
    public class CelulaController : Controller
    {
        private DB db = new DB();

        // GET: Celula
        public async Task<ActionResult> Index()
        {
            var celulas = await db.celula.Include(c => c.EnderecoCelula).ToListAsync();
            return View(celulas);
        }

        // GET: Celula/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Celula celula = await db.celula.FindAsync(id);
            if (celula == null)
            {
                return HttpNotFound();
            }
            return View(celula);
        }

        // GET: Celula/Create
        public ActionResult Create(string tipo)
        {
            Celula celula = null;

            if (tipo == "Celula_Adolescente") celula = new Celula_Adolescente();
            if (tipo == "Celula_Adulto") celula = new Celula_Adulto();
            if (tipo == "Celula_Casado") celula = new Celula_Casado();
            if (tipo == "Celula_Crianca") celula = new Celula_Crianca();
            if (tipo == "Celula_Jovem") celula = new Celula_Jovem();

            celula.EnderecoCelula = new EnderecoCelula();

            ViewBag.IdCelula = new SelectList(db.EnderecoCelula, "IdEnderecoCelula", "Cep");
            return View(celula);
        }

        #region Create-Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CelulaAdolescente(Celula_Adolescente celula)
        {
            if (celula.IdCelula == 0) return await Salvar(celula);
            else return await Editar(celula);           
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CelulaAdulto(Celula_Adulto celula)
        {
            if (celula.IdCelula == 0) return await Salvar(celula);
            else return await Editar(celula);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Celula_Jovem(Celula_Jovem celula)
        {
            if (celula.IdCelula == 0) return await Salvar(celula);
            else return await Editar(celula);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Celula_Jovem(Celula_Crianca celula)
        {
            if (celula.IdCelula == 0) return await Salvar(celula);
            else return await Editar(celula);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Celula_Jovem(Celula_Casado celula)
        {
            if (celula.IdCelula == 0) return await Salvar(celula);
            else return await Editar(celula);
        }

        private async Task<ActionResult> Editar(Celula celula)
        {
            db.Entry(celula).State = EntityState.Modified;
            db.Entry(celula.EnderecoCelula).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private async Task<ActionResult> Salvar(Celula celula)
        {
            db.celula.Add(celula);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        #endregion
       

        // GET: Celula/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Celula celula = await db.celula.Include(c => c.EnderecoCelula).FirstAsync(c => c.IdCelula == id);
            if (celula == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCelula = new SelectList(db.EnderecoCelula, "IdEnderecoCelula", "Pais", celula.IdCelula);
            return View(celula);
        }        

        // GET: Celula/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Celula celula = await db.celula.FindAsync(id);
            if (celula == null)
            {
                return HttpNotFound();
            }
            return View(celula);
        }

        // POST: Celula/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Celula celula = await db.celula.FindAsync(id);
            db.celula.Remove(celula);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backup/igreja_dll/Site/Controllers/MinisterioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RepositorioEF;
using business.classes.Abstrato;
using business.classes.Ministerio;

namespace Site.Controllers
{
    [Authorize(Roles ="Admin")]
    public class MinisterioController : Controller
    {
        private DB db = new DB();

        // GET: Ministerio
        public async Task<ActionResult> Index()
        {
            return View(await db.ministerio.ToListAsync());
        }

        // GET: Ministerio/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ministerio ministerio = await db.ministerio.FindAsync(id);
            if (ministerio == null)
            {
                return HttpNotFound();
            }
            return View(ministerio);
        }

        // GET: Ministerio/Create
        public ActionResult Create(string tipo)
        {
            Ministerio ministerio = null;
            if (tipo == "Lider_Celula") ministerio = new Lider_Celula();
            if (tipo == "Lider_Celula_Treinamento") ministerio = new Lider_Celula_Treinamento();
            if (tipo == "Lider_Ministerio") ministerio = new Lider_Ministerio();
            if (tipo == "Lider_Ministerio_Treinamento") ministerio = new Lider_Ministerio_Treinamento();
            if (tipo == "Supervisor_Celula") ministerio = new Supervisor_Celula();
            if (tipo == "Supervisor_Celula_Treinamento") ministerio = new Supervisor_Celula_Treinamento();
            if (tipo == "Supervisor_Ministerio") ministerio = new Supervisor_Ministerio();
            if (tipo == "Supervisor_Ministerio_Treinamento") ministerio = new Supervisor_Ministerio_Treinamento();
            
            return View(ministerio);
        }
       
        #region Create-Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LiderCelula(Lider_Celula ministerio)
        {
            if (ministerio.IdMinisterio == 0) return await Create(ministerio);
            else return await Editar(ministerio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LiderCelulaTreinamento(Lider_Celula_Treinamento ministerio)
        {
            if (ministerio.IdMinisterio == 0) return await Create(ministerio);
            else return await Editar(ministerio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LiderMinisterio(Lider_Ministerio ministerio)
        {
            if (ministerio.IdMinisterio == 0) return await Create(ministerio);
            else return await Editar(ministerio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LiderMinisterioTreinamento(Lider_Ministerio_Treinamento ministerio)
        {
            if (ministerio.IdMinisterio == 0) return await Create(ministerio);
            else return await Editar(ministerio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SupervisorCelula(Supervisor_Celula ministerio)
        {
            if (ministerio.IdMinisterio == 0) return await Create(ministerio);
            else return await Editar(ministerio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SupervisorCelula(Supervisor_Celula_Treinamento ministerio)
        {
            if (ministerio.IdMinisterio == 0) return await Create(ministerio);
            else return await Editar(ministerio);
        }

        
        private async Task<ActionResult> Editar(Ministerio ministerio)
        {
            db.Entry(ministerio).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [ValidateAntiForgeryToken]
        private async Task<ActionResult> Create(Ministerio ministerio)
        {
            db.ministerio.Add((Ministerio)ministerio);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        #endregion

        // GET: Ministerio/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ministerio ministerio = await db.ministerio.FindAsync(id);
            if (ministerio == null)
            {
                return HttpNotFound();
            }
            return View(ministerio);
        }
       

        // GET: Ministerio/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ministerio ministerio = await db.ministerio.FindAsync(id);
            if (ministerio == null)
            {
                return HttpNotFound();
            }
            return View(ministerio);
        }

        // POST: Ministerio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Ministerio ministerio = await db.ministerio.FindAsync(id);
            db.ministerio.Remove(ministerio);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backup/igreja_dll/Site/Controllers/ReuniaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RepositorioEF;
using business.classes;

namespace Site.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ReuniaoController : Controller
    {
        private DB db = new DB();

        // GET: Reuniao
        public async Task<ActionResult> Index()
        {
            return View(await db.reuniao.ToListAsync());
        }

        // GET: Reuniao/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reuniao reuniao = await db.reuniao.FindAsync(id);
            if (reuniao == null)
            {
                return HttpNotFound();
            }
            return View(reuniao);
        }

        // GET: Reuniao/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reuniao/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "IdReuniao,Data_reuniao,Horario_inicio,Horario_fim,Local_reuniao")] Reuniao reuniao)
        {
            if (ModelState.IsValid)
            {
                db.reuniao.Add(reuniao);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(reuniao);
        }

        // GET: Reuniao/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reuniao reuniao = await db.reuniao.FindAsync(id);
            if (reuniao == null)
            {
                return HttpNotFound();
            }
            return View(reuniao);
        }

        // POST: Reuniao/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "IdReuniao,Data_reuniao,Horario_inicio,Horario_fim,Local_reuniao")] Reuniao reuniao)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reuniao).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(reuniao);
        }

        // GET: Reuniao/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reuniao reuniao = await db.reuniao.FindAsync(id);
            if (reuniao == null)
            {
                return HttpNotFound();
            }
            return View(reuniao);
        }

        // POST: Reuniao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Reuniao reuniao = await db.reuniao.FindAsync(id);
            db.reuniao.Remove(reuniao);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backup/igreja_dll/Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Ministerios", "Ministerios", "Home")</li>
                    <li>@Html.ActionLink("Celulas", "Celulas", "Home")</li>
                    <li>@Html.ActionLink("Reuniões", "Reunioes", "Home")</li>
                    <li>@Html.ActionLink("Programações", "Programacao", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin</a>
                        <ul class="dropdown-menu">
                        <li>@Html.ActionLink("lista de Celulas", "Index", "Celula", null, null)</li>
                        <li>@Html.ActionLink("Lista de Reuniões", "Index", "Reuniao", null, null)</li>
                        <li>@Html.ActionLink("Lista de Ministérios", "Index", "Ministerio", null, null)</li>

                        <li>@Html.ActionLink("Cadastrar Lider de Celula", "Create", "Ministerio", new { tipo = "Lider_Celula" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Lider de Celula em Treinamento", "Create", "Ministerio", new { tipo = "Lider_Celula_Treinamento" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Lider de Ministério", "Create", "Ministerio", new { tipo = "Lider_Ministerio" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Lider de Ministério em treinamento", "Create", "Ministerio", new { tipo = "Lider_Ministerio_Treinamento" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Supervisor de Celula", "Create", "Ministerio", new { tipo = "Supervisor_Celula" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Supervisor de Celula em treinamento", "Create", "Ministerio", new { tipo = "Supervisor_Celula_Treinamento" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Supervisor de Ministério", "Create", "Ministerio", new { tipo = "Supervisor_Ministerio" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Supervisor de Ministério em Treinamento", "Create", "Ministerio", new { tipo = "Supervisor_Ministerio_Treinamento" }, null)</li>

                        <li>@Html.ActionLink("Cadastrar Celula para Adolescente", "Create", "Celula", new { tipo = "Celula_Adolescente" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Celula para Adulto", "Create", "Celula", new { tipo = "Celula_Adulto" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Celula para Jovem", "Create", "Celula", new { tipo = "Celula_Jovem" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Celula para Criança", "Create", "Celula", new { tipo = "Celula_Crianca" }, null)</li>
                        <li>@Html.ActionLink("Cadastrar Celula para Casados", "Create", "Celula", new { tipo = "Celula_casado" }, null)</li>

                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>